// lib/garage/catalog.ts
// Redline Garage - Comprehensive Parts Catalog & Factory Recommendations

import { CarConfig, PartCategory, PartSpec, TuningSettings } from "./types";

export const PART_CATEGORIES: { id: PartCategory; name: string; icon: string }[] = [
  { id: "chassis", name: "车架底盘", icon: "Car" },
  { id: "engine", name: "动力引擎", icon: "Zap" },
  { id: "transmission", name: "变速箱", icon: "Gauge" },
  { id: "tires", name: "竞技轮胎", icon: "Disc" },
  { id: "nos", name: "氮气增压", icon: "Flame" },
  { id: "aero", name: "空力套件", icon: "Wind" },
  { id: "exhaust", name: "排气系统", icon: "Activity" },
];

export const PARTS_CATALOG: Record<PartCategory, PartSpec[]> = {
  chassis: [
    {
      id: "chassis_muscle",
      category: "chassis",
      name: "烈马 1969 经典管阵车架",
      subtitle: "V8 经典后驱肌肉平台",
      description: "纯正美式重型车架，坚固抗扭，后驱起步重心自然下压，带经典的霸气方正机盖肌肉轮廓。",
      weightKg: 1320,
      style: "muscle",
    },
    {
      id: "chassis_tuner",
      category: "chassis",
      name: "战神 R-Spec 赛道轻量化底盘",
      subtitle: "东瀛流线竞技单体壳",
      description: "铝合金与高强钢混合结构，重心低且前后配重均衡，兼顾极速切割与起步平稳性。",
      weightKg: 1140,
      style: "tuner",
    },
    {
      id: "chassis_hyper",
      category: "chassis",
      name: "幽灵 Apex 极速碳纤维单体壳",
      subtitle: "超跑原型超低风阻",
      description: "航空级全碳纤维座舱与一体化空气动力学导流道，极致轻量，极速狂飙的首选。",
      weightKg: 940,
      style: "hyper",
    },
    {
      id: "chassis_dragster",
      category: "chassis",
      name: "地狱火 Pro-Mod 直线特装架",
      subtitle: "专业 1/4 英里加长底盘",
      description: "加长轴距、带后防滚架与极限轻量化骨架，专为承受 2000 匹以上狂暴扭矩打造。",
      weightKg: 820,
      style: "dragster",
    },
  ],

  engine: [
    {
      id: "engine_i4_turbo",
      category: "engine",
      name: "4G63-R 2.0L 直列四缸双涡轮",
      subtitle: "高转激进小钢炮",
      description: "自重轻、红线转速高达 9000 RPM，中后段涡轮建压后推力源源不断，声浪清脆高亢。",
      weightKg: 140,
      baseHp: 540,
      maxRpm: 9000,
      torqueNm: 620,
      engineType: "inline4_turbo",
      soundProfile: "tuner_i4",
    },
    {
      id: "engine_v6_twin",
      category: "engine",
      name: "VR38-GT 3.8L V6 双双涡轮",
      subtitle: "均衡战神动力总成",
      description: "全转速域线性大扭矩，双大号陶瓷滚珠轴承涡轮，响应极快，直线加速中的中流砥柱。",
      weightKg: 195,
      baseHp: 820,
      maxRpm: 8400,
      torqueNm: 950,
      engineType: "v6_twin_turbo",
      soundProfile: "tuner_i4",
    },
    {
      id: "engine_v8_supercharged",
      category: "engine",
      name: "Hemi 6.2L 机械增压 V8 巨兽",
      subtitle: "低转起步扭矩收割机",
      description: "带外露皮带轮与硕大进气口（Blower），怠速如低音炮，油门一碰即爆发 1300Nm 瞬间扭矩！",
      weightKg: 260,
      baseHp: 1100,
      maxRpm: 7600,
      torqueNm: 1320,
      engineType: "v8_blower",
      soundProfile: "muscle_v8",
    },
    {
      id: "engine_v12_quad",
      category: "engine",
      name: "Quad-Turbo 6.0L W12 狂暴总成",
      subtitle: "四涡轮 1600 匹工业奇迹",
      description: "拥有无穷无尽的高速功率储备，400 米冲线尾速杀手，每一次高转呼啸都令人战栗。",
      weightKg: 310,
      baseHp: 1550,
      maxRpm: 8800,
      torqueNm: 1750,
      engineType: "v12_quad",
      soundProfile: "super_v12",
    },
    {
      id: "engine_dual_ev",
      category: "engine",
      name: "Dual-Flux 1300kW 永磁同步电驱",
      subtitle: "0 延迟 1750 匹瞬时扭矩",
      description: "双电机碳纤维转子，从 0 速度起即可输出全额 2000Nm 狂暴扭矩，弹射起步毫无顿挫。",
      weightKg: 240,
      baseHp: 1750,
      maxRpm: 18000,
      torqueNm: 2050,
      engineType: "dual_ev",
      soundProfile: "ev_whine",
    },
  ],

  transmission: [
    {
      id: "trans_4speed_h",
      category: "transmission",
      name: "4速 经典宽齿比手动箱",
      subtitle: "大扭矩宽容度之选",
      description: "齿比分布宽，极速档位高，换挡顿挫 180ms，耐造耐操，极适合大排量 V8 引擎。",
      weightKg: 75,
      gearCount: 4,
      gearRatios: [3.2, 1.9, 1.3, 0.95],
      finalDrive: 3.55,
      shiftDelayMs: 180,
    },
    {
      id: "trans_6speed_dct",
      category: "transmission",
      name: "6速 赛道级双离合 (DCT)",
      subtitle: "无缝极速换挡 60ms",
      description: "高响应双离合机构，换挡动力近乎零中断，齿比紧密衔接，转速始终锁定在最大功率带。",
      weightKg: 88,
      gearCount: 6,
      gearRatios: [3.8, 2.4, 1.7, 1.25, 0.95, 0.75],
      finalDrive: 3.73,
      shiftDelayMs: 60,
    },
    {
      id: "trans_2speed_glide",
      category: "transmission",
      name: "2速 Powerglide 专业直线箱",
      subtitle: "顶级 1/4 英里神器",
      description: "直线赛车传奇：仅 1 挡弹射起步、2 挡直接冲线！全赛程仅需换 1 次挡，动力中断时间降至极限！",
      weightKg: 58,
      gearCount: 2,
      gearRatios: [1.82, 1.0],
      finalDrive: 4.1,
      shiftDelayMs: 40,
    },
    {
      id: "trans_7speed_seq",
      category: "transmission",
      name: "7速 气动序列式竞技箱",
      subtitle: "极速高转密度王",
      description: "超密齿比，支持全油门不松油无离合升挡，换挡 50ms，适合高转四涡轮和战神引擎。",
      weightKg: 82,
      gearCount: 7,
      gearRatios: [3.9, 2.6, 1.9, 1.45, 1.15, 0.92, 0.76],
      finalDrive: 3.65,
      shiftDelayMs: 50,
    },
  ],

  tires: [
    {
      id: "tires_street",
      category: "tires",
      name: "高性能街道运动胎 (285/35 R19)",
      subtitle: "均衡耐磨街道配置",
      description: "复合胎面花纹，抓地系数 1.10，不易过度升温，适合日常改装与新手熟悉赛道。",
      weightKg: 44,
      gripCoefficient: 1.1,
      optimalTempC: 60,
      tireType: "street",
    },
    {
      id: "tires_semi_slick",
      category: "tires",
      name: "半热熔赛道光头胎 (Semi-Slick)",
      subtitle: "快速升温抓地强化",
      description: "抓地系数 1.38，少许热身烧胎后即可达到极佳附着力，起步打滑显著减少。",
      weightKg: 40,
      gripCoefficient: 1.38,
      optimalTempC: 75,
      tireType: "semi_slick",
    },
    {
      id: "tires_drag_radial",
      category: "tires",
      name: "专业直线厚壁大肥胎 (Drag Radials 15寸)",
      subtitle: "低压起步弹性变形锁死地面",
      description: "超宽后胎与高胎壁，可低胎压运行，起步瞬间褶皱吸地，抓地系数 1.72，直线弹射标配！",
      weightKg: 52,
      gripCoefficient: 1.72,
      optimalTempC: 90,
      tireType: "drag_radial",
    },
    {
      id: "tires_sticky_compound",
      category: "tires",
      name: "VHT 树脂胶顶级热熔大宽胎",
      subtitle: "终极物理粘性抓地 1.95",
      description: "专业直线赛道级配方，烧胎后胎面宛如强力胶水，可承受 1800 匹全油门起步而不打滑！",
      weightKg: 56,
      gripCoefficient: 1.95,
      optimalTempC: 105,
      tireType: "drag_radial",
    },
  ],

  nos: [
    {
      id: "nos_none",
      category: "nos",
      name: "无氮气 / 纯自吸自压",
      subtitle: "纯粹内燃机输出",
      description: "不携带氮气气瓶，节省额外配重 0kg，挑战纯机械物理极限。",
      weightKg: 0,
      nosShotHp: 0,
      nosCapacitySec: 0,
    },
    {
      id: "nos_single_50",
      category: "nos",
      name: "单瓶干式喷射系统 (NOS-75)",
      subtitle: "+90 HP 额外爆发 (持续 6秒)",
      description: "铝合金小气罐，起步后段补充马力，蓝色喷焰，温和且持久。",
      weightKg: 12,
      nosShotHp: 90,
      nosCapacitySec: 6.0,
    },
    {
      id: "nos_dual_150",
      category: "nos",
      name: "双瓶湿式大流量喷射 (NOS-220)",
      subtitle: "+240 HP 狂暴推进 (持续 5.2秒)",
      description: "双罐并联直喷进气歧管，伴随浓烈蓝色尾焰与刺耳泄压气流，中后程速度飙升！",
      weightKg: 22,
      nosShotHp: 240,
      nosCapacitySec: 5.2,
    },
    {
      id: "nos_quad_monster",
      category: "nos",
      name: "四联装极速直喷怪兽 (NOS-500)",
      subtitle: "+480 HP 破纪录核动力 (持续 4.5秒)",
      description: "极限四联装高压钢瓶，瞬间注入极冷氧化亚氮，让尾速大屏直接起飞！",
      weightKg: 38,
      nosShotHp: 480,
      nosCapacitySec: 4.5,
    },
  ],

  aero: [
    {
      id: "aero_stock",
      category: "aero",
      name: "纯素外壳 (低风阻极速型)",
      subtitle: "极简低阻 Cd 0.28",
      description: "去除多余尾翼阻力，极速阻力最小，适合冲刺超高尾速记录。",
      weightKg: 0,
      dragCoefficientDelta: -0.04,
      downforceMultiplier: 0.8,
      hasWheelieBar: false,
    },
    {
      id: "aero_gt_wing",
      category: "aero",
      name: "碳纤维 GT-3 竞速大尾翼",
      subtitle: "高速下压力 +180kg",
      description: "高强度轻量化碳纤维天鹅颈尾翼，在 200km/h 以上提供充沛下压力，抑制车尾漂浮。",
      weightKg: 8,
      dragCoefficientDelta: 0.03,
      downforceMultiplier: 1.4,
      hasWheelieBar: false,
    },
    {
      id: "aero_widebody",
      category: "aero",
      name: "全车宽体套件 + 前唇风刀",
      subtitle: "高速稳定性大幅提升",
      description: "肌肉宽体翼子板包围与侧裙，加宽轮距，增强起步导向与抓地稳定性。",
      weightKg: 18,
      dragCoefficientDelta: 0.02,
      downforceMultiplier: 1.3,
      hasWheelieBar: false,
    },
    {
      id: "aero_wheelie_bar",
      category: "aero",
      name: "防翘头小轮 (Wheelie Bar) + 尾部减速伞",
      subtitle: "大马力起步弹射神器",
      description: "车尾延伸支撑轮架，牢牢锁住起步抬头角度，将 100% 动力转化为向前推进力！",
      weightKg: 24,
      dragCoefficientDelta: 0.04,
      downforceMultiplier: 1.2,
      hasWheelieBar: true,
    },
  ],

  exhaust: [
    {
      id: "exhaust_street",
      category: "exhaust",
      name: "双出回压运动排气",
      subtitle: "浑厚低调日常改装",
      description: "不锈钢双出管口，声浪饱满浑厚，回压均衡。",
      weightKg: 18,
      exhaustFlowBonus: 0.0,
      flameLevel: 1,
    },
    {
      id: "exhaust_side_exit",
      category: "exhaust",
      name: "机盖/车侧直排喷火套件 (Side Dumps)",
      subtitle: "换挡回火伴随金蓝火舌",
      description: "超短歧管直接从车身侧方喷出，排气背压归零，马力提升 +4%，换挡时伴随剧烈爆鸣！",
      weightKg: 9,
      exhaustFlowBonus: 0.04,
      flameLevel: 3,
    },
    {
      id: "exhaust_titanium_straight",
      category: "exhaust",
      name: "全钛合金大口径直通排气 (Titanium Cannon)",
      subtitle: "极致轻量化与金属高音",
      description: "整段航空钛合金手工鱼鳞焊，重量骤降，排气通畅度拉满，马力提升 +6%！",
      weightKg: 6,
      exhaustFlowBonus: 0.06,
      flameLevel: 2,
    },
  ],
};

// 预设车漆配色
export const PAINT_COLORS: { name: string; hex: string; desc: string }[] = [
  { name: "烈焰赤红", hex: "#e62117", desc: "经典赛道速度红" },
  { name: "曜石酷黑", hex: "#18181c", desc: "暗夜潜行低调质感" },
  { name: "竞速明黄", hex: "#f5a623", desc: "极具侵略性的亮黄" },
  { name: "狂暴电青", hex: "#00d2ff", desc: "氮气冰蓝高光" },
  { name: "液态钛银", hex: "#c0c4cc", desc: "金属机械切削本色" },
  { name: "极光紫魅", hex: "#8a2be2", desc: "夜间车库反光流彩" },
  { name: "翡翠暗绿", hex: "#0e5a3c", desc: "英伦经典竞技绿" },
  { name: "哑光战术灰", hex: "#4b4f58", desc: "重型防滚装甲灰" },
];

// 默认初始装配
export const DEFAULT_CAR_CONFIG: CarConfig = {
  chassisId: "chassis_muscle",
  engineId: "engine_v8_supercharged",
  transmissionId: "trans_2speed_glide",
  tiresId: "tires_drag_radial",
  nosId: "nos_dual_150",
  aeroId: "aero_wheelie_bar",
  exhaustId: "exhaust_side_exit",
  paintColor: "#e62117",
  paintFinish: "metallic",
  tuning: {
    boostMultiplier: 1.15,
    redlineRpm: 7600,
    finalDriveRatio: 3.9,
    gear1Ratio: 2.1,
    gear2Ratio: 1.0,
    gear3Ratio: 1.35,
    gear4Ratio: 1.0,
    gear5Ratio: 0.8,
    gear6Ratio: 0.65,
    tirePressurePsi: 18,
    nosDurationSec: 5.0,
    nosTriggerRpm: 4500,
    wingAngleDeg: 8,
    suspensionStiffness: 1.0,
  },
};

// 厂队推荐配置生成函数 (Factory Spec recommendation)
export function getFactoryRecommendedTuning(config: CarConfig): TuningSettings {
  const engine = PARTS_CATALOG.engine.find((e) => e.id === config.engineId);
  const trans = PARTS_CATALOG.transmission.find((t) => t.id === config.transmissionId);
  const tires = PARTS_CATALOG.tires.find((t) => t.id === config.tiresId);

  const baseRedline = engine?.maxRpm ?? 7500;
  const isEv = engine?.engineType === "dual_ev";
  const defaultFinalDrive = trans?.finalDrive ?? 3.73;

  let tirePsi = 22;
  if (tires?.tireType === "drag_radial") tirePsi = 16;
  else if (tires?.tireType === "semi_slick") tirePsi = 24;

  return {
    boostMultiplier: isEv ? 1.0 : 1.2,
    redlineRpm: baseRedline,
    finalDriveRatio: defaultFinalDrive,
    gear1Ratio: trans?.gearRatios?.[0] ?? 2.8,
    gear2Ratio: trans?.gearRatios?.[1] ?? 1.6,
    gear3Ratio: trans?.gearRatios?.[2] ?? 1.2,
    gear4Ratio: trans?.gearRatios?.[3] ?? 0.95,
    gear5Ratio: trans?.gearRatios?.[4] ?? 0.8,
    gear6Ratio: trans?.gearRatios?.[5] ?? 0.65,
    tirePressurePsi: tirePsi,
    nosDurationSec: 4.5,
    nosTriggerRpm: isEv ? 2000 : Math.round(baseRedline * 0.55),
    wingAngleDeg: 10,
    suspensionStiffness: 1.0,
  };
}

// 快速预设配置
export const PRESET_BUILDS: { name: string; desc: string; config: CarConfig }[] = [
  {
    name: "烈火战车 · 1/4英里 7秒终结者",
    desc: "V8 机械增压 + 2速 Powerglide + 防翘头小轮 + 双瓶氮气",
    config: {
      chassisId: "chassis_muscle",
      engineId: "engine_v8_supercharged",
      transmissionId: "trans_2speed_glide",
      tiresId: "tires_drag_radial",
      nosId: "nos_dual_150",
      aeroId: "aero_wheelie_bar",
      exhaustId: "exhaust_side_exit",
      paintColor: "#e62117",
      paintFinish: "metallic",
      tuning: {
        boostMultiplier: 1.25,
        redlineRpm: 7600,
        finalDriveRatio: 4.1,
        gear1Ratio: 1.82,
        gear2Ratio: 1.0,
        gear3Ratio: 1.3,
        gear4Ratio: 1.0,
        gear5Ratio: 0.8,
        gear6Ratio: 0.65,
        tirePressurePsi: 15,
        nosDurationSec: 4.8,
        nosTriggerRpm: 4200,
        wingAngleDeg: 6,
        suspensionStiffness: 0.9,
      },
    },
  },
  {
    name: "极速幽灵 · 尾速 400km/h 杀手",
    desc: "W12 四涡轮 + 6速双离合 + 全碳底盘 + 四联氮气",
    config: {
      chassisId: "chassis_hyper",
      engineId: "engine_v12_quad",
      transmissionId: "trans_6speed_dct",
      tiresId: "tires_sticky_compound",
      nosId: "nos_quad_monster",
      aeroId: "aero_gt_wing",
      exhaustId: "exhaust_titanium_straight",
      paintColor: "#00d2ff",
      paintFinish: "metallic",
      tuning: {
        boostMultiplier: 1.35,
        redlineRpm: 8800,
        finalDriveRatio: 3.4,
        gear1Ratio: 3.2,
        gear2Ratio: 2.1,
        gear3Ratio: 1.5,
        gear4Ratio: 1.15,
        gear5Ratio: 0.9,
        gear6Ratio: 0.72,
        tirePressurePsi: 20,
        nosDurationSec: 4.5,
        nosTriggerRpm: 5000,
        wingAngleDeg: 12,
        suspensionStiffness: 1.2,
      },
    },
  },
  {
    name: "静默闪电 · 零延迟瞬间弹射",
    desc: "双电机 1750 匹 + 顶级热熔胎 + 碳纤维单体壳",
    config: {
      chassisId: "chassis_hyper",
      engineId: "engine_dual_ev",
      transmissionId: "trans_2speed_glide",
      tiresId: "tires_sticky_compound",
      nosId: "nos_none",
      aeroId: "aero_widebody",
      exhaustId: "exhaust_street",
      paintColor: "#f5a623",
      paintFinish: "chrome",
      tuning: {
        boostMultiplier: 1.1,
        redlineRpm: 18000,
        finalDriveRatio: 3.8,
        gear1Ratio: 2.2,
        gear2Ratio: 1.0,
        gear3Ratio: 1.3,
        gear4Ratio: 1.0,
        gear5Ratio: 0.8,
        gear6Ratio: 0.65,
        tirePressurePsi: 22,
        nosDurationSec: 0,
        nosTriggerRpm: 0,
        wingAngleDeg: 10,
        suspensionStiffness: 1.1,
      },
    },
  },
];
